### ISSUE TITLE
Newest update to rack 1.6.0 beta throwing vague NoMethodError

### ISSUE THREAD

**Issue by Jastor11** [learn-co-curriculum/sinatra-fwitter-5-sessions#3]
Addressed here, but it can be fixed by inserting gem 'rack', '1.5.2' into gemfile

http://stackoverflow.com/questions/26255022/why-is-sinatras-show-exceptions-rb-file-crashing-when-i-raise-a-runtimeerror

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
